### ISSUE TITLE
Image Credit Caption

### ISSUE THREAD

**Issue by pettazz** [WarrantyNowVoid/jekyll-wnv#62]
Add an optional "credit:" key to the image object on posts that allows adding a credit link to the source/owner of the image if it's not ours. 

Use the key to display a floating link at the edge of the image container to the credit source, if it's set.

**Comment by pettazz** [comment]
Example usage: 

````
image:
  headliner: assets/img/lol/vacation-bad.jpg
  credit: 
      title: Original photo by NeONBRAND on Unsplash
      link: https://unsplash.com/@neonbrand
````
